Add missing rdk-vlanmanager json-c dependency
This is needed to fix build errors:
| RdkVlanBridgingManager/source/TR-181/middle_layer_src/vlan_eth_hal.c:61:10: fatal error: json-c/json.h: No such file or directory
|    61 | #include <json-c/json.h>
|       |          ^~~~~~~~~~~~~~~
| compilation terminated.
| Makefile:514: recipe for target 'libRdkVlanManager_middle_layer_src_la-vlan_eth_hal.lo' failed

Change-Id: I882fbe704bf228ab278136576c49dda504f47b7d