REFPLTB-3260 : Import Build Failure on CcspPandM/+/110013
Reason for change : Added fix for below errors,
../rdkb/components/opensource/ccsp/CcspPandM/source-arm/TR-181/board_sbapi/cosa_common_util.c:648:19:
error: implicit declaration of function 'Send_WebPANotification_prefix'
[-Werror=implicit-function-declaration]
         int ret = Send_WebPANotification_prefix(IPV6_PREFIX, prefix,
previous_prefix);
& pam process is not running at run-time
241113-08:23:47.221329 [mod=PAM, lvl=WARN] [tid=106994] Unable to load
library -- libtr181.so
241113-08:23:47.221428 [mod=PAM, lvl=WARN] [tid=106994]
cause:/usr/lib/libtr181.so: undefined symbol:
Send_WebPANotification_prefix
Test procedure : Attached in JIRA
Risk : Low

Change-Id: I4d132ef9f02e8693acf2ed840cddd42a5af82485
Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>